app = 'smartfix-wa-bot'
primary_region = 'sin'

[build]
  builder = "paketobuildpacks/builder-jammy-base" # Using a specific Paketo builder
  buildpacks = [
    "paketo-buildpacks/nodejs" # Explicitly use the Node.js buildpack
  ]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = "wwebjs_data"
  destination = "/wwebjs_data"