app = 'smartfix-wa-bot'
primary_region = 'sin'

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = 'stop'
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = "wwebjs_data"
  destination = "/wwebjs_data"