# fly.toml app configuration file generated for smartfix-wa-bot on 2025-06-02T11:11:46+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'smartfix-wa-bot'
primary_region = 'sin'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
  
[build]
  builder = "paketobuildpacks/builder:base"
  
[[mounts]]
  source = "wwebjs_data"
  destination = "/wwebjs_data"
